import { Project, PortfolioData } from "../types";

export const projects: PortfolioData = {
  personal: [
    {
      id: 1,
      title: "EM BREVE",
      description:
        "Novos projetos em desenvolvimento. Fique atento para as próximas atualizações!",
      technologies: [],
      status: "Em Breve",
      category: "Cloud",
      startDate: null,
      endDate: null,
      image: null,
      highlights: [],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 101,
      title: "E-book Cuidados Pós-Operatórios (Infoproduto)",
      description:
        "Este projeto nasceu da intersecção estratégica entre a minha trajetória de quase uma década na área da Saúde e a minha transição para o setor de Tecnologia. O objetivo foi validar o uso de Inteligência Artificial na criação de um infoproduto de alta qualidade, transformando conhecimento técnico especializado em um manual prático, acessível e comercializável.",
      technologies: [
        "IA Generativa",
        "Engenharia de Prompt",
        "Curadoria de Conteúdo",
        "Infoprodutos",
        "Hotmart",
      ],
      status: "Concluído",
      category: "Infoproduto",
      startDate: "2026-01-10",
      endDate: "2026-01-20",
      image: "/ebook.jpg",
      highlights: [
        "Expertise de Domínio: Aplicação de anos de experiência clínica em reabilitação para garantir a precisão técnica das orientações pós-cirúrgicas",
        "Engenharia de Prompt e IA: Utilização de ferramentas de IA para estruturar, organizar e otimizar o conteúdo, reduzindo o tempo de produção sem perder a autoridade científica",
        "Visão de Produto: Desenvolvimento focado na jornada do usuário (paciente), transformando orientações complexas em um guia passo a passo para facilitar a recuperação",
        "Transição de Carreira na Prática: Demonstração real de como a tecnologia pode potencializar setores tradicionais, criando soluções prontas para o mercado digital",
        "Curadoria de conteúdo técnico especializado em Saúde",
        "Utilização estratégica de IA Generativa para desenvolvimento de produtos",
        "Comunicação clara e focada no cliente final",
      ],
      featured: true,
      links: {
        demo: null,
        github: null,
        case_study: null,
      },
    },
    {
      id: 100,
      title: "CityShield: Segurança Urbana Inteligente e Resposta Automatizada",
      description:
        "Solução de vanguarda para cidades inteligentes, integrando monitoramento físico e digital para resposta coordenada a incidentes. Arquitetura Event-driven e Serverless para processar fluxos de vídeo e logs de rede em tempo real, utilizando IA para identificar ameaças e orquestrar ações imediatas com órgãos de segurança.",
      technologies: [
        "AWS Lambda",
        "Amazon Bedrock",
        "Amazon Kinesis",
        "Amazon Rekognition",
        "Amazon GuardDuty",
        "AWS WAF",
        "Amazon SNS",
        "Amazon DynamoDB",
        "Amazon S3",
        "Amazon CloudWatch",
        "Serverless",
        "Event-Driven",
      ],
      status: "Em Andamento",
      category: "Cloud",
      startDate: "2026-01-05",
      endDate: null,
      image: "/imagensCloud/projeto-colaborativo-tcc.jpeg",
      highlights: [
        "Monitoramento de vídeo em tempo real com Amazon Kinesis Video Streams e Amazon Rekognition",
        "Análise preditiva e GenAI com Amazon Bedrock para tomada de decisão estratégica",
        "Segurança multicamada com Amazon GuardDuty e AWS WAF para proteção de borda",
        "Orquestração Serverless com AWS Lambda garantindo desacoplamento entre detecção e resposta",
        "Notificação crítica via Amazon SNS para Polícia, SAMU e Bombeiros em tempo real",
        "Observabilidade e auditoria centralizada no Amazon CloudWatch",
        "Persistência escalável com Amazon DynamoDB e Amazon S3 para evidências",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
      team: {
        role: "Cloud Architect",
        description: "Arquitetura seguindo AWS Well-Architected Framework",
        size: 4,
      },
    },
    {
      id: 2,
      title:
        "Provisionamento de Infraestrutura de Rede e Computação Isolada na AWS (VPC & EC2)",
      description:
        "Este projeto consistiu na criação de uma arquitetura de rede personalizada e isolada na nuvem AWS, seguida pelo deploy de uma instância de computação. O objetivo foi demonstrar o domínio sobre o isolamento de recursos, controle de tráfego e provisionamento de servidores dentro de uma infraestrutura controlada.",
      technologies: [
        "Amazon VPC",
        "Amazon EC2",
        "Security Groups",
        "Subnets",
        "CIDR",
        "Route Tables",
        "Linux",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2026-01-01",
      endDate: "2026-01-12",
      image: "/imagensCloud/criacao-vpc.jpeg",
      highlights: [
        "Criação de VPC personalizada (ID: vpc-09496947ae64fd171) para hospedar recursos de forma isolada",
        "Habilitação de resoluções de DNS e nomes de host para comunicação interna",
        "Implementação de sub-rede pública 'Public Subnet 2' no bloco CIDR 10.0.0.0/16",
        "Configuração do 'Web Security Group' (ID: sg-038ebd4471953373a) como firewall virtual",
        "Definição estratégica de regras de entrada e saída para tráfego autorizado",
        "Deploy da instância 'Web Server 1' (ID: i-06a2d5dd117d67420) com t3.micro",
        "Utilização do Amazon Linux 2023 como sistema operacional base",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 3,
      title: "Implementação de Acesso Seguro com Bastion Host na AWS",
      description:
        "Estruturação de uma arquitetura de rede segura na AWS para isolar um servidor web de acessos públicos diretos. Utilizei um Bastion Host como ponto de entrada controlado e configurei regras de Security Group para garantir SSH seguro exclusivamente via EC2 Instance Connect, reforçando políticas de acesso baseadas em IAM.",
      technologies: [
        "Amazon EC2",
        "Bastion Host",
        "EC2 Instance Connect",
        "Security Groups",
        "IAM",
        "AWS CLI",
        "SSH",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2026-01-01",
      endDate: "2026-01-31",
      image: "/imagensCloud/bastion-host.jpeg",
      highlights: [
        "Implementação de arquitetura de segurança com Bastion Host como único ponto de entrada",
        "Configuração de acesso SSH seguro via EC2 Instance Connect com autenticação IAM",
        "Definição de Security Groups restritivos para controle granular de tráfego",
        "Isolamento do servidor web de acessos públicos diretos",
        "Aplicação de políticas de acesso baseadas em IAM para auditoria e compliance",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 4,
      title: "Gestão de Identidade e Acesso na AWS com IAM",
      description:
        "Implementação completa de gestão de identidade e acesso na AWS utilizando IAM. O projeto incluiu a criação de usuários, grupos, políticas customizadas e a aplicação do princípio do menor privilégio para garantir segurança e conformidade.",
      technologies: [
        "AWS IAM",
        "IAM Policies",
        "IAM Groups",
        "IAM Users",
        "AWS Organizations",
        "Security Best Practices",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2025-12-20",
      endDate: "2025-12-30",
      image: "/imagensCloud/iam-cloud.jpeg",
      highlights: [
        "Criação de estrutura de usuários e grupos seguindo boas práticas de segurança",
        "Implementação de políticas customizadas com princípio do menor privilégio",
        "Configuração de MFA para usuários administrativos",
        "Documentação de políticas de acesso para auditoria",
        "Integração com AWS Organizations para gerenciamento multi-conta",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 5,
      title: "Infraestrutura Escalável e Alta Disponibilidade na AWS",
      description:
        "Projeto de arquitetura de alta disponibilidade utilizando múltiplas zonas de disponibilidade, Auto Scaling Groups e Application Load Balancer. A infraestrutura foi projetada para suportar picos de tráfego e garantir resiliência.",
      technologies: [
        "Amazon EC2",
        "Auto Scaling Group",
        "Application Load Balancer",
        "Multi-AZ",
        "Amazon CloudWatch",
        "Amazon SNS",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2025-12-15",
      endDate: "2025-12-25",
      image: "/imagensCloud/infraestrutura-aws.jpeg",
      highlights: [
        "Configuração de Auto Scaling Group com políticas de escalonamento dinâmico",
        "Implementação de Application Load Balancer para distribuição de tráfego",
        "Deploy em múltiplas zonas de disponibilidade para alta resiliência",
        "Monitoramento com CloudWatch e alertas via SNS",
        "Otimização de custos com instâncias spot e reserved",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 6,
      title: "Processamento Serverless de Arquivos com AWS Lambda",
      description:
        "Implementação de pipeline serverless para processamento automático de arquivos utilizando AWS Lambda, S3 e Python. O sistema processa arquivos enviados ao S3 e armazena metadados no DynamoDB.",
      technologies: [
        "AWS Lambda",
        "Amazon S3",
        "Amazon DynamoDB",
        "Python",
        "IAM",
        "CloudWatch Logs",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2025-12-01",
      endDate: "2025-12-15",
      image: "/imagensCloud/processamento-de-arquivos.jpeg",
      highlights: [
        "Desenvolvimento de função Lambda em Python para processamento de arquivos",
        "Configuração de trigger S3 para execução automática",
        "Armazenamento de metadados no DynamoDB",
        "Implementação de logs e monitoramento com CloudWatch",
        "Aplicação de políticas IAM com menor privilégio",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 7,
      title: "Infraestrutura como Código com AWS CloudFormation",
      description:
        "Projeto de automação de infraestrutura utilizando AWS CloudFormation para provisionar recursos de forma declarativa e reproduzível. Templates YAML foram criados para deploy de VPC, EC2 e recursos relacionados.",
      technologies: [
        "AWS CloudFormation",
        "YAML",
        "Amazon VPC",
        "Amazon EC2",
        "Infrastructure as Code",
        "AWS CLI",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2025-11-20",
      endDate: "2025-11-30",
      image: "/imagensCloud/cloudformation-aws.jpeg",
      highlights: [
        "Criação de templates CloudFormation em YAML para infraestrutura completa",
        "Automação de deploy de VPC, subnets e security groups",
        "Implementação de outputs para referência entre stacks",
        "Versionamento de templates para controle de mudanças",
        "Deploy automatizado via AWS CLI",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
    {
      id: 8,
      title: "Armazenamento Compartilhado com Amazon EFS",
      description:
        "Implementação de sistema de arquivos compartilhado utilizando Amazon EFS para múltiplas instâncias EC2. O projeto demonstra alta disponibilidade e persistência de dados entre servidores.",
      technologies: [
        "Amazon EFS",
        "Amazon EC2",
        "Amazon VPC",
        "NFS",
        "Linux",
        "EC2 Launch Template",
      ],
      status: "Concluído",
      category: "Cloud",
      startDate: "2025-11-01",
      endDate: "2025-11-10",
      image: "/imagensCloud/EFS-Fernanda.jpeg",
      highlights: [
        "Configuração de VPC personalizada com sub-redes públicas em diferentes zonas (us-west-2)",
        "Criação do EFS-Fernanda para acesso simultâneo de múltiplos servidores com persistência de dados",
        "Padronização com EC2 Launch Template para lançamentos rápidos e consistentes",
        "Instalação do amazon-efs-utils e montagem do sistema de arquivos via NFS/TLS",
        "Validação de dados com criação de arquivos e verificação de persistência entre instâncias",
        "Arquitetura de alta disponibilidade para compartilhamento de dados entre servidores",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
    },
  ],
  collaborative: [
    {
      id: 100,
      title: "CityShield: Segurança Urbana Inteligente e Resposta Automatizada",
      description:
        "Solução de vanguarda para cidades inteligentes, integrando monitoramento físico e digital para resposta coordenada a incidentes. Arquitetura Event-driven e Serverless para processar fluxos de vídeo e logs de rede em tempo real, utilizando IA para identificar ameaças e orquestrar ações imediatas com órgãos de segurança.",
      technologies: [
        "AWS Lambda",
        "Amazon Bedrock",
        "Amazon Kinesis",
        "Amazon Rekognition",
        "Amazon GuardDuty",
        "AWS WAF",
        "Amazon SNS",
        "Amazon DynamoDB",
        "Amazon S3",
        "Amazon CloudWatch",
        "Serverless",
        "Event-Driven",
      ],
      status: "Em Andamento",
      category: "Cloud",
      startDate: "2026-01-01",
      endDate: null,
      image: "/imagensCloud/projeto-colaborativo-tcc.jpeg",
      highlights: [
        "Monitoramento de vídeo em tempo real com Amazon Kinesis Video Streams e Amazon Rekognition",
        "Análise preditiva e GenAI com Amazon Bedrock para tomada de decisão estratégica",
        "Segurança multicamada com Amazon GuardDuty e AWS WAF para proteção de borda",
        "Orquestração Serverless com AWS Lambda garantindo desacoplamento entre detecção e resposta",
        "Notificação crítica via Amazon SNS para Polícia, SAMU e Bombeiros em tempo real",
        "Observabilidade e auditoria centralizada no Amazon CloudWatch",
        "Persistência escalável com Amazon DynamoDB e Amazon S3 para evidências",
      ],
      featured: true,
      links: {
        github: null,
        case_study: null,
      },
      team: {
        role: "Cloud Architect",
        description: "Arquitetura seguindo AWS Well-Architected Framework",
        size: 4,
      },
    },
  ],
};
